# Generated by Django 5.2.17 on 2026-08-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
