# Generated by Django 5.2.17 on 2026-09-09 13:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0003_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='accepted_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='provisioned',
            field=models.BooleanField(default=False),
        ),
    ]
